/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cartasresponsivas.login;


import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author desan
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     * @throws java.io.IOException
     */
    public Login() throws IOException {
        
        try {
            UIManager.setLookAndFeel(new FlatMaterialLighterIJTheme());
        } catch (UnsupportedLookAndFeelException ex) {
        }
        // Cargar la imagen
        
        
        initComponents();
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd MMMM yyyy (EEEE)"); 
        jLabel_Welcome_date.setText("Hoy es: " + dtf.format(LocalDate.now()));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bg = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jButton_CrearPdf = new javax.swing.JButton();
        jButton_ActualizarPdf = new javax.swing.JButton();
        jButton_CrearPdf2 = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        jLabel_Welcome = new javax.swing.JLabel();
        jLabel_Welcome_date = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(800, 500));

        menu.setBackground(new java.awt.Color(255, 153, 153));
        menu.setMaximumSize(new java.awt.Dimension(25767, 28767));
        menu.setPreferredSize(new java.awt.Dimension(2, 500));
        menu.setLayout(new java.awt.GridBagLayout());

        jButton_CrearPdf.setBackground(new java.awt.Color(255, 204, 204));
        jButton_CrearPdf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_CrearPdf.setForeground(new java.awt.Color(0, 0, 0));
        jButton_CrearPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPdf.png"))); // NOI18N
        jButton_CrearPdf.setText("Crear carta");
        jButton_CrearPdf.setBorder(null);
        jButton_CrearPdf.setBorderPainted(false);
        jButton_CrearPdf.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton_CrearPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CrearPdfActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 129;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        menu.add(jButton_CrearPdf, gridBagConstraints);

        jButton_ActualizarPdf.setBackground(new java.awt.Color(255, 204, 204));
        jButton_ActualizarPdf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_ActualizarPdf.setForeground(new java.awt.Color(0, 0, 0));
        jButton_ActualizarPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPdf.png"))); // NOI18N
        jButton_ActualizarPdf.setText("Actualizar Carta");
        jButton_ActualizarPdf.setBorder(null);
        jButton_ActualizarPdf.setBorderPainted(false);
        jButton_ActualizarPdf.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton_ActualizarPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ActualizarPdfActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 94;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        menu.add(jButton_ActualizarPdf, gridBagConstraints);

        jButton_CrearPdf2.setBackground(new java.awt.Color(255, 204, 204));
        jButton_CrearPdf2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_CrearPdf2.setForeground(new java.awt.Color(0, 0, 0));
        jButton_CrearPdf2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPdf.png"))); // NOI18N
        jButton_CrearPdf2.setText("Buscar carta");
        jButton_CrearPdf2.setBorder(null);
        jButton_CrearPdf2.setBorderPainted(false);
        jButton_CrearPdf2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton_CrearPdf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CrearPdf2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 119;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 117, 6);
        menu.add(jButton_CrearPdf2, gridBagConstraints);

        header.setBackground(new java.awt.Color(236, 236, 236));
        header.setForeground(new java.awt.Color(204, 204, 204));

        jLabel_Welcome.setFont(new java.awt.Font("Madimi One", 1, 24)); // NOI18N
        jLabel_Welcome.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Welcome.setText("Hola, bienvenido a cartas responsivas");

        jLabel_Welcome_date.setFont(new java.awt.Font("Madimi One", 0, 18)); // NOI18N
        jLabel_Welcome_date.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Welcome_date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Welcome_date.setText("jLabel2");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_Welcome_date, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(jLabel_Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Welcome_date, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CrearPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CrearPdfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_CrearPdfActionPerformed

    private void jButton_ActualizarPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ActualizarPdfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ActualizarPdfActionPerformed

    private void jButton_CrearPdf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CrearPdf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_CrearPdf2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Login().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton_ActualizarPdf;
    private javax.swing.JButton jButton_CrearPdf;
    private javax.swing.JButton jButton_CrearPdf2;
    private javax.swing.JLabel jLabel_Welcome;
    private javax.swing.JLabel jLabel_Welcome_date;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
